"""Change id columns

Revision ID: 152236cc5775
Revises: 25811d78ede
Create Date: 2012-07-21 21:59:10.193402

"""

# revision identifiers, used by Alembic.
revision = '152236cc5775'
down_revision = '25811d78ede'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "user" ALTER COLUMN drive_id TYPE varchar(255)')
    op.execute('ALTER TABLE "user" ALTER COLUMN dropbox_id TYPE varchar(255)')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "user" ALTER COLUMN drive_id TYPE bigint')
    op.execute('ALTER TABLE "user" ALTER COLUMN dropbox_id TYPE bigint')
    ### end Alembic commands ###
