"""id chunksasd

Revision ID: 16a3478ee1f6
Revises: 4dd59f1e03f4
Create Date: 2012-07-22 10:07:39.807468

"""

# revision identifiers, used by Alembic.
revision = '16a3478ee1f6'
down_revision = '4dd59f1e03f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
