"""Add parity column to chunks

Revision ID: 2162634184ff
Revises: 481f57d8925a
Create Date: 2012-07-21 19:57:08.199430

"""

# revision identifiers, used by Alembic.
revision = '2162634184ff'
down_revision = '481f57d8925a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('parity', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunk', 'parity')
    ### end Alembic commands ###
