"""Chance id column types from bigint to string

Revision ID: 25811d78ede
Revises: 3532c7515372
Create Date: 2012-07-21 21:53:41.683823

"""

# revision identifiers, used by Alembic.
revision = '25811d78ede'
down_revision = '3532c7515372'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
