"""Set nullable to true on chunk service

Revision ID: 37a591dfef9f
Revises: ad0aebcb18a
Create Date: 2012-07-22 07:26:30.313647

"""

# revision identifiers, used by Alembic.
revision = '37a591dfef9f'
down_revision = 'ad0aebcb18a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunk', u'service', 
               existing_type=sa.VARCHAR(length=32), 
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunk', u'service', 
               existing_type=sa.VARCHAR(length=32), 
               nullable=False)
    ### end Alembic commands ###
