"""Add auth token to users

Revision ID: 42fdd0e6f5b0
Revises: 2162634184ff
Create Date: 2012-07-21 20:20:44.440962

"""

# revision identifiers, used by Alembic.
revision = '42fdd0e6f5b0'
down_revision = '2162634184ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth_token', sa.String(length=36), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'auth_token')
    ### end Alembic commands ###
