"""Add useful columns

Revision ID: 47ff999d8c6e
Revises: 152236cc5775
Create Date: 2012-07-22 04:48:32.255782

"""

# revision identifiers, used by Alembic.
revision = '47ff999d8c6e'
down_revision = '152236cc5775'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('service', sa.String(length=32), nullable=False))
    op.add_column('file', sa.Column('modified_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=32), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_column('file', 'modified_at')
    op.drop_column('chunk', 'service')
    ### end Alembic commands ###
