"""bigints

Revision ID: 55aa0348c271
Revises: 37a591dfef9f
Create Date: 2012-07-22 08:58:00.447511

"""

# revision identifiers, used by Alembic.
revision = '55aa0348c271'
down_revision = '37a591dfef9f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dropbox_total', sa.BigInteger(), nullable=True))
    op.add_column('user', sa.Column('drive_quota', sa.BigInteger(), nullable=True))
    op.add_column('user', sa.Column('drive_total', sa.BigInteger(), nullable=True))
    op.add_column('user', sa.Column('dropbox_quota', sa.BigInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'dropbox_quota')
    op.drop_column('user', 'drive_total')
    op.drop_column('user', 'drive_quota')
    op.drop_column('user', 'dropbox_total')
    ### end Alembic commands ###
