"""Add name to chunks

Revision ID: ad0aebcb18a
Revises: 47ff999d8c6e
Create Date: 2012-07-22 05:47:23.029337

"""

# revision identifiers, used by Alembic.
revision = 'ad0aebcb18a'
down_revision = '47ff999d8c6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('name', sa.String(length=255), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunk', 'name')
    ### end Alembic commands ###
