/* Generated by mkuoff_t.c */

#ifndef _UOFF_T_H
#define _UOFF_T_H

#ifndef SIZEOF_CHAR
#define SIZEOF_CHAR 1
#endif

#ifndef SIZEOF_SHORT
#define SIZEOF_SHORT 2
#endif

#ifndef SIZEOF_INT
#define SIZEOF_INT 4
#endif

#ifndef SIZEOF_LONG
#define SIZEOF_LONG 8
#endif

#ifndef SIZEOF_LONG_LONG
#define SIZEOF_LONG_LONG 8
#endif

#ifndef SIZEOF_VOID_P
#define SIZEOF_VOID_P 8
#endif

#ifndef SIZEOF_SIZE_T
#define SIZEOF_SIZE_T 8
#endif

#ifndef SIZEOF_OFF_T
#define SIZEOF_OFF_T 8
#endif

#define SIZEOF_UOFF_T 8
typedef uint64_t uoff_t;

#endif	/* _UOFF_T_H */

